### ISSUE TITLE
T-RMM Client Map: "stdout" does not exist

### ISSUE THREAD

**Issue by RhysCorgi** [dinger1986/TRMM-Grafana#25]
Hi,

So I just installed this verbatim from the installation guide, setup a location grabber in T-RMM that pulls the location of devices and stores it in a custom variable (just to make sure that wasn't the issue), and I'm still getting this error:

db query error: pq: column "stdout" does not exist

Which I take to mean that the column "stdout" does not exist in the database as a field, however I have no idea what to do about this.

**Comment by dinger1986** [comment]
if you can fix it please PR, I dont actively develop the dashboards but happy to take PRs for them.

**Comment by nini57** [comment]
Hello,
I've the same error, when launch the script I've too error

Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "http\client.py", line 921, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\TacticalRMM\1905764307.py", line 41, in <module>
    response = urlopen(url)
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1379, in http_open
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Can you help me ? please
Thank's in advance
